/**
 * DESIGN DOCUMENT - NOT ACTUAL IMPLEMENTATION
 *
 * This file demonstrates the planned TypeScript/JavaScript SDK API design.
 * The actual implementation will be created using napi-rs bindings.
 *
 * Installation (when published):
 *   npm install @pctx/sdk
 *
 * Key Features:
 * - Full TypeScript support with auto-generated types
 * - Same clean API as Python SDK
 * - Async-first design (returns Promises)
 * - Zero-copy data transfer between JS and Rust
 * - Config file support
 */

import { Pctx } from '@pctx/sdk';

// Initialize with config (auto-connects to all servers)
// Allowed hosts are automatically derived from server URLs
const client = new Pctx({
  servers: [
    { name: 'banking', url: 'http://localhost:3000' },
    { name: 'crm', url: 'http://localhost:3001' },
  ]
});

// Or load from config file
const client2 = await Pctx.fromConfig('pctx.json');

// List all available functions across all servers
const functions = client.functions.list();
console.log(functions);  // TypeScript declarations

// Get detailed info about specific functions
const details = client.functions.getDetails(['Banking.getBalance', 'Crm.getUser']);
console.log(details);  // Full type definitions

// Execute TypeScript code with full MCP access
const result = await client.execute(`
  async function run() {
    // All registered servers are available as namespaces
    const balance = await Banking.getBalance({ account_id: "123" });
    const user = await Crm.getUser({ id: balance.user_id });

    return {
      user: user.name,
      balance: balance.amount
    };
  }
`);

if (result.success) {
  console.log('Output:', result.output);
  console.log('Logs:', result.stdout);
} else {
  console.error('Error:', result.error);
}

// Access individual server info
for (const server of client.servers) {
  console.log(`${server.name}: ${server.tools.length} tools`);
}


// =============================================================================
// Type Definitions (auto-generated by napi-rs)
// =============================================================================

export interface PctxConfig {
  /** List of MCP servers to connect to */
  servers: ServerConfig[];
  /** Note: Allowed hosts are automatically derived from server URLs */
}

export interface ServerConfig {
  /** Unique name for this server (used as namespace) */
  name: string;
  /** URL of the MCP server */
  url: string;
  /** Optional environment variables for the server */
  env?: Record<string, string>;
}

export interface ExecutionResult {
  /** Whether execution completed successfully */
  success: boolean;
  /** The return value from the run() function */
  output?: any;
  /** Standard output from the execution */
  stdout: string;
  /** Standard error from the execution */
  stderr: string;
  /** Error message if execution failed */
  error?: string;
}

export interface ServerInfo {
  /** Server name */
  name: string;
  /** TypeScript namespace for this server's functions */
  namespace: string;
  /** Server description */
  description: string;
  /** Server URL */
  url: string;
  /** Available tools/functions */
  tools: ToolInfo[];
}

export interface ToolInfo {
  /** Function name */
  name: string;
  /** Optional description */
  description?: string;
  /** JSON schema for input parameters */
  inputSchema: string;
  /** Optional JSON schema for return type */
  outputSchema?: string;
}

/**
 * Function introspection interface
 */
export class Functions {
  /**
   * List all available functions with TypeScript declarations
   *
   * Returns pretty-printed TypeScript namespace declarations showing
   * all available functions from connected MCP servers.
   */
  list(): string;

  /**
   * Get detailed type info for specific functions
   *
   * @param functions - Array of function names in format "Namespace.functionName"
   *                    e.g., ["Banking.getBalance", "Crm.getUser"]
   * @returns TypeScript declarations with full parameter and return types
   */
  getDetails(functions: string[]): string;
}

/**
 * Main PCTX client for MCP tool execution
 */
export class Pctx {
  /**
   * Initialize with config object
   *
   * @param config - Configuration with servers and optional allowed hosts
   */
  constructor(config: PctxConfig);

  /**
   * Load from config file
   *
   * @param path - Path to pctx.json config file
   * @returns Promise resolving to initialized Pctx instance
   */
  static fromConfig(path: string): Promise<Pctx>;

  /**
   * Execute TypeScript code with MCP access
   *
   * The code must define an async function named `run()` which will be
   * called and its return value captured.
   *
   * @param code - TypeScript code containing: async function run() { ... }
   * @returns Promise resolving to execution result
   */
  execute(code: string): Promise<ExecutionResult>;

  /** Access to function listing and details */
  readonly functions: Functions;

  /** List of connected servers */
  readonly servers: ServerInfo[];
}


// =============================================================================
// Usage with AI Frameworks (Anthropic/OpenAI)
// =============================================================================

import Anthropic from '@anthropic-ai/sdk';

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const pctx = await Pctx.fromConfig('pctx.json');

const conversation: Array<{ role: string; content: string }> = [
  { role: 'user', content: 'Get my account balance and user profile' }
];

// Provide available functions to the AI
const availableFunctions = pctx.functions.list();

const response = await anthropic.messages.create({
  model: 'claude-sonnet-4-20250514',
  max_tokens: 16000,
  messages: [
    ...conversation,
    { role: 'user', content: `Available MCP functions:\n${availableFunctions}` }
  ]
});

// Extract and execute code from thinking blocks
for (const block of response.content) {
  if (block.type === 'thinking' && block.thinking.includes('async function run()')) {
    const result = await pctx.execute(block.thinking);

    if (result.success) {
      conversation.push({
        role: 'assistant',
        content: `Result: ${JSON.stringify(result.output)}`
      });
    } else {
      conversation.push({
        role: 'assistant',
        content: `Error: ${result.error}\n${result.stderr}`
      });
    }
  }
}
